### ISSUE TITLE
npm run production Module Error cannot find unsupported.js

### ISSUE THREAD

**Issue by abhi-cognitivo** [cretueusebiu/laravel-vue-spa#131]
Hi, I was able to compile it, but now I am getting this error. Any ideas?

```
My-MacBook:laravel-vue-spa user$ npm run production
module.js:549
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:153:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)

```

**Comment by cretueusebiu** [comment]
Try the usual `rm -rf node_modules` and `yarn` again.

**Comment by abhi-cognitivo** [comment]
Thanks for the quick reply. But no. 

I think this happens because I upgraded to Yarn 1.10.1?? When I run Yarn, I am getting warnings:
```
warning "@vue/cli-plugin-eslint > eslint-loader@2.0.0" has unmet peer dependency "webpack@>=2.0.0 <5.0.0".
warning "@vue/eslint-config-standard > eslint-config-standard@11.0.0" has unmet peer dependency "eslint@>=4.18.0".
warning "@vue/eslint-config-standard > eslint-plugin-import@2.9.0" has unmet peer dependency "eslint@2.x - 4.x".
warning "@vue/eslint-config-standard > eslint-plugin-node@6.0.1" has unmet peer dependency "eslint@>=3.1.0".
warning "@vue/eslint-config-standard > eslint-plugin-standard@3.1.0" has unmet peer dependency "eslint@>=3.19.0".
```

Could this be an issue?

**Comment by cretueusebiu** [comment]
What Node version do you have ?

**Comment by cretueusebiu** [comment]
Seems to work fine with the latest Yarn version on my machine with Node 8.10.

Try this:
https://stackoverflow.com/questions/44363066/error-cannot-find-module-lib-utils-unsupported-js-while-using-ionic

**Comment by abhi-cognitivo** [comment]
Sorry about that. Yes you are right. Investigating, it seems that a newer version of Node fixes this.
