### ISSUE TITLE
Getting Uncaught TypeError: Cannot read property 'toLowerCase' of undefined after running npm run dev or watch

### ISSUE THREAD

**Issue by hazem-taha** [cretueusebiu/laravel-vue-spa#274]
![image](https://user-images.githubusercontent.com/46519001/85741764-5eba1c80-b70b-11ea-8d15-5ab0b95d0d5e.png)

```
TypeError: Cannot read property 'length' of undefined
    at /Users/abcuser/code/prog/node_modules/laravel-mix-versionhash/src/index.js:209:42
    at /Users/abcuser/code/prog/node_modules/laravel-mix/src/Dispatcher.js:34:47
    at Array.forEach (<anonymous>)
    at Dispatcher.fire (/Users/abcuser/code/prog/node_modules/laravel-mix/src/Dispatcher.js:34:28)
    at Mix.dispatch (/Users/abcuser/code/prog/node_modules/laravel-mix/src/Mix.js:118:25)
    at /Users/abcuser/code/prog/node_modules/laravel-mix/src/builder/webpack-plugins.js:43:46
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/abcuser/code/prog/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/abcuser/code/prog/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/abcuser/code/prog/node_modules/webpack/lib/Compiler.js:304:22
    at Compiler.emitRecords (/Users/abcuser/code/prog/node_modules/webpack/lib/Compiler.js:499:39)
    at /Users/abcuser/code/prog/node_modules/webpack/lib/Compiler.js:298:10
    at /Users/abcuser/code/prog/node_modules/webpack/lib/Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/abcuser/code/prog/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/abcuser/code/prog/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/abcuser/code/prog/node_modules/webpack/lib/Compiler.js:482:27
    at /Users/abcuser/code/prog/node_modules/neo-async/async.js:2818:7
    at done (/Users/abcuser/code/prog/node_modules/neo-async/async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/abcuser/code/prog/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at /Users/abcuser/code/prog/node_modules/webpack/lib/Compiler.js:464:33
    at /Users/abcuser/code/prog/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (fs.js:163:23)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

and this is my package.json

```
{
  "private": true,
  "scripts": {
    "dev": "npm run development",
    "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "npm run development -- --watch",
    "watch-poll": "npm run watch -- --watch-poll",
    "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --disable-host-check --config=node_modules/laravel-mix/setup/webpack.config.js",
    "prod": "npm run production",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "lint": "eslint --fix --ext .js,.vue resources/js"
  },
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.28",
    "@fortawesome/free-brands-svg-icons": "^5.13.0",
    "@fortawesome/free-regular-svg-icons": "^5.13.0",
    "@fortawesome/free-solid-svg-icons": "^5.13.0",
    "@fortawesome/vue-fontawesome": "^0.1.9",
    "blueimp-file-upload": "^9.18.0",
    "bootstrap-daterangepicker": "^2.1.25",
    "bootstrap-validator": "^0.11.9",
    "bootswatch": "^4.5.0",
    "chart.js": "^2.8.0",
    "chartist": "^0.11.0",
    "ckeditor": "^4.6.2",
    "datatables.net": "^1.10.15",
    "datatables.net-bs": "^2.1.1",
    "datatables.net-buttons": "^1.3.1",
    "datatables.net-buttons-bs": "^1.3.1",
    "dragula": "^3.7.2",
    "dropzone": "^5.1.1",
    "editable-table": "*",
    "element-ui": "^2.13.2",
    "filepond": "^4.7.1",
    "filepond-plugin-image-preview": "^4.4.0",
    "firebase": "^7.13.1",
    "fullcalendar": "^3.4.0",
    "intl-tel-input": "^16.0.7",
    "ion-rangeslider": "^2.3.0",
    "jquery-bar-rating": "^1.2.2",
    "jquery-filepond": "^1.0.0",
    "js-cookie": "^2.2.1",
    "laravel-echo": "^1.5.4",
    "laravel-vue-datatable": "^0.5.11",
    "moment": "^2.24.0",
    "perfect-scrollbar": "^0.7.1",
    "pusher-js": "^5.0.1",
    "select2": "^4.0.3",
    "slick-carousel": "^1.6.0",
    "sweetalert2": "^8.19.0",
    "tether": "^1.4.0",
    "timepicker": "^1.11.15",
    "toastr": "^2.1.4",
    "vform": "^1.0.1",
    "vue-carousel": "^0.18.0",
    "vue-chartjs": "^3.4.2",
    "vue-form-wizard": "^0.8.4",
    "vue-full-calendar": "^2.7.0",
    "vue-i18n": "^8.18.1",
    "vue-meta": "^1.6.0",
    "vue-multiselect": "^2.1.6",
    "vue-router": "^3.3.2",
    "vue-slick": "^1.1.15",
    "vuex": "^3.4.0",
    "vuex-router-sync": "^5.0.0"
  },
  "devDependencies": {
    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
    "@babel/preset-env": "^7.10.2",
    "axios": "^0.18.1",
    "babel-eslint": "^10.1.0",
    "bootstrap": "^4.5.0",
    "cross-env": "^5.2.1",
    "eslint": "^5.16.0",
    "eslint-config-standard": "^12.0.0",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-node": "^9.2.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.1",
    "eslint-plugin-vue": "^5.2.3",
    "jquery": "^3.5.1",
    "laravel-mix": "^4.1.4",
    "laravel-mix-versionhash": "^1.1.3",
    "lodash": "^4.17.15",
    "popper.js": "^1.16.1",
    "resolve-url-loader": "^2.3.1",
    "sass": "^1.26.8",
    "sass-loader": "^7.3.1",
    "vue": "^2.6.11",
    "vue-template-compiler": "^2.6.11",
    "webpack-bundle-analyzer": "^3.8.0"
  }
}

```

**Comment by hazem-taha** [comment]
Solved. 

It was because I added my own components to `components/index.js` file 
But why it crashes, idk.
