### ISSUE TITLE
[webpack-cli] Error: spawn Unknown system error -86

### ISSUE THREAD

**Issue by ntqtuan** [cretueusebiu/laravel-vue-spa#321]
I build a project laravel + vuejs in macos.
I follow the steps:

laravel new blog
cd blog
composer require laravel/ui
php artisan ui vue
npm install && npm run dev
and then asked for the following
```

       Additional dependencies must be installed. This will only take a moment.

	Running: npm install vue-loader@^15.9.7 --save-dev --legacy-peer-deps

	Finished. Please run Mix again.
```

I run : npm install vue-loader@^15.9.7 --save-dev --legacy-peer-deps
finally i run the following command 'npm run dev' .
always get below error:
```
                         
[webpack-cli] Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:415:11)
    at spawn (node:child_process:698:9)
    at Object.execFile (node:child_process:325:17)
    at Object.module.exports.fileCommandJson (/Users/panda/Sites/blog/node_modules/node-notifier/lib/utils.js:88:13)
    at NotificationCenter.notifyRaw (/Users/panda/Sites/blog/node_modules/node-notifier/notifiers/notificationcenter.js:81:11)
    at WebpackNotifierPlugin.compilationDone (/Users/panda/Sites/blog/node_modules/webpack-notifier/index.js:129:14)
    at _next1 (eval at create (/Users/panda/Sites/blog/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:39:1)
    at eval (eval at create (/Users/panda/Sites/blog/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:63:1) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn'
}
```

**Comment by ntqtuan** [comment]
please someone help me with this error
i'm so desperate
