### ISSUE TITLE
Error: Cannot find module 'is-windows' on 'npm run watch'

### ISSUE THREAD

**Issue by dwinjnr** [cretueusebiu/laravel-vue-spa#95]
Godwin Junior@GodwinJunior-PC MINGW64 /c/xampp/htdocs/laravel-vue-spa-master (master)
$ npm run watch

> @ watch C:\xampp\htdocs\laravel-vue-spa-master
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

module.js:549
    throw err;
    ^

Error: Cannot find module 'is-windows'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\xampp\htdocs\laravel-vue-spa-master\node_modules\cross-env\dist\command.js:11:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ watch: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Godwin Junior\AppData\Roaming\npm-cache\_logs\2018-04-30T09_38_06_908Z-debug.log

**Comment by cretueusebiu** [comment]
This is more a issue related to Laravel Mix.

Try installing the dependencies with yarn.
